apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
  name: app-operator
  namespace: giantswarm
spec:
  catalog: control-plane-test-catalog
  config:
    configMap:
      name: app-operator-values
      namespace: giantswarm
  kubeConfig:
    inCluster: true
  name: app-operator
  namespace: giantswarm
  version: {{ .Values.appOperator.version }}
